### ISSUE TITLE
Trio reverts to looking for old G7 CGM and misses readings

### ISSUE THREAD

**Issue by aug0211** [nightscout/Trio#354] opened 2024-07-19 11:54 UTC
## Describe the bug
Trio reverts to a prior G7 sensor seemingly at random. The current sensor is not seen and BG readings are dropped. Missed readings, yellow loops and red loops may occur. This normally self heals after a handful of missed readings.

## To Reproduce
1. Pair a G7 sensor
2. When the G7's time is up, pair a new G7 sensor as instructed by Dexcom
3. Observe, when you see missed readings, tap into Trio's CGM view and interrogate whether it is using dates and info from your prior G7 sensor

## Expected behavior
Trio should pull BG readings from the actively paired sensor.

## Screenshots
![image](https://github.com/user-attachments/assets/0a327fe3-655f-4877-84ff-b201c355b50b)![image](https://github.com/user-attachments/assets/62e15787-ff40-4d86-9f60-622c4f7a2396)![image](https://github.com/user-attachments/assets/b5a16347-ef64-48f3-b07d-65ff3921bd26)![image](https://github.com/user-attachments/assets/01728ed1-5250-4814-9740-f63cf4fb818c)

### Smartphone:
* Hardware: iphone 13 Mini
* OS Version: iOS 17.5

### Pump:
* Manufacturer: Insulet
* Model: Omnipod Dash

### CGM:
* Device: Dexcom G7
* Manager app: Dexcom App

## Additional context
A number of uses have anecdotally reported more missed readings with Trio than expected. Perhaps this is the cause.

Light discussion on this in [Discord chat](https://discord.com/channels/1020905149037813862/1239982832026255521/1262769164003840040) with 3 people experiencing and discussing this.

**Comment by mkellerman-relativity** [comment] 2024-07-25 16:37
This has happened a few times to me as well.
This happened 8 days into a new sensor. 

![IMG_0132](https://github.com/user-attachments/assets/f9bdc851-1ebb-479b-b5ea-3d05daebae48)
![IMG_0133](https://github.com/user-attachments/assets/d3179009-4d1e-413c-a56b-27d32234f90f)

**Comment by tredair7** [comment] 2024-07-25 23:11
I don’t have any screenshots but we’ve also experienced this issue.

**Comment by t1dude** [comment] 2024-08-04 15:03
The root cause seems to be that the CGM Manager does not properly write the new sensor's Bluetooth ID to the CGMManagerState.plist file after it has picked up the new ID from the Dexcom app.

As long as you don't reboot your phone or otherwise kill the Trio app, the CGM Manager seems to be storing the new ID somewhere else (memory?) and does not need to read the ID from the CGMManagerState.plist file.

After a phone reboot, Trio will read from the CGMManagerState.plist file, where it will find the old sensor's Bluetooth ID and start to look for the old sensor.

I suspect this issue might also affect Loop and iAPS.

Documented with 16 numbered screen shots.

1 - Old Sensor in Dexcom App:
![1 - Old Sensor in Dexcom App](https://github.com/user-attachments/assets/18b924dd-2d6b-4b14-83fa-b3d551d8e145)

2 - Old Sensor in Trio:
![2 - Old Sensor in Trio](https://github.com/user-attachments/assets/eef9f4e9-bbbf-4830-a669-86f7000bf2fc)

3 - Old Sensor in CGMManagerState plist file:
![3 - Old Sensor in CGMManagerState plist file](https://github.com/user-attachments/assets/b56b3af8-7f46-4dfe-bb7e-b3328b71a34c)

4 - Old Sensor in Bluetooth Settings:
![4 - Ols Sensor in Bluetooth Settings](https://github.com/user-attachments/assets/3564cdea-933e-4dc5-9d18-3b12eb32fad3)

5 - New Sensor added to Dexcom App:
![5 - New Sensor added to Dexcom App](https://github.com/user-attachments/assets/28813f40-54b9-43f5-b07d-bfab153fad7c)

6 - Old and New Sensors in Bluetooth Settings:
![6 - Old and New Sensors in Bluetooth Settings](https://github.com/user-attachments/assets/a83c6405-e204-42c5-bb25-96c9ac7b0f2c)

7 - Old Sensor removed from Bluetooth Settings:
![7 - Old Sensor removed from Bluetooth Settings](https://github.com/user-attachments/assets/9ce5fb53-f6a6-476c-9e6a-8d36909ae62a)

8 - New Sensor picked up by Trio:
![8 - New Sensor picked up by Trio](https://github.com/user-attachments/assets/1225589e-070d-4150-ba68-c40255778f01)

9 - Old Sensor still in CGMManagerState plist file after Trio picked up new sensor:
![9 - Old Sensor still in CGMManagerState plist file after Trio picked up new sensor](https://github.com/user-attachments/assets/28646b68-93f4-4d10-9f30-3a5844f2bb3d)

10 - CGMManagerState plist file was does not have new timestamp:
![10 - CGMManagerState plist file was does not have new timestamp](https://github.com/user-attachments/assets/4d25d204-51dd-4aa5-bf9f-8c2c535606bd)

11 - CGMManagerState plist file has new timestamp after phone reboot:
![11 - CGMManagerState plist file has new timestamp after phone reboot](https://github.com/user-attachments/assets/32dacb4e-f675-46cb-beab-715945e53b07)

12 - CGMManagerState plist file still has old sensor ID after reboot and new timestamp:
![12 - CGMManagerState plist file still has old sensor ID after reboot and new timestamp](https://github.com/user-attachments/assets/f58598d4-5261-4790-ae1f-3104cafa14b2)

13 - Trio searching for old sensor after reboot:
![13 - Trio searching for old sensor after reboot](https://github.com/user-attachments/assets/1664a1fc-d6f7-48a2-8137-7ed80c715680)

14 - Deleted and re-added CGM in Trio - now paired with new sensor:
![14 - Deleted and re-added CGM in Trio - now paired with new sensor](https://github.com/user-attachments/assets/02bffefd-a711-4575-b981-107e6c66e1ce)

15 - CGMManagerState plist file has new timestamp after re-adding CGM in Trio:
![15 - CGMManagerState plist file has new timestamp after re-adding CGM in Trio](https://github.com/user-attachments/assets/ec5d1cec-772a-483d-88d8-9c41bee00dc3)

16 - CGMManagerState plist file has new sensor ID:
![16 - CGMManagerState plist file has new sensor ID](https://github.com/user-attachments/assets/c0b1d0ef-adaf-4efe-a4bf-c8ade068f037)

**Comment by aug0211** [comment] 2024-08-04 15:35
Great finds! It sounds like the plist is correctly updated when adding (or re-adding) the CGM “as new” but not when a new CGM is “auto detected”.

One fix is to of course write to the plist on every connection, but this is IO heavy. We could also read from the plist and if the sensor ID doesn’t match, then update plist (also expensive to read from plist every cycle, assuming we aren’t already doing this (? have not looked).

Do we have any natural hooks to identify that a new sensor is being read, to then trigger the plist update so we can avoid that IO if possible? Of course if it’s already required this is a moot concern :)

**Comment by marionbarker** [comment] 2024-08-04 16:58
I think this is Trio only.
My Loop phone rebooted yesterday when I updated to iOS 17.6 and had not trouble picking up the G7.
My display of the CGMManagerState.plist looks a bit different in that the DXCM## value is not visible.

![IMG_EB928320C5B1-1](https://github.com/user-attachments/assets/e2fe7d8f-0686-4e92-b80b-f533be21fdce)

**Comment by aug0211** [comment] 2024-08-04 17:09
That is very good news as it means we're more empowered to fix this directly I think.

**Comment by t1dude** [comment] 2024-08-04 19:15
I agree @aug0211 . Dan and I are troubleshooting now and will try to apply a fix. But we have to coordinate testing to avoid wasting sensors :)

**Comment by dnzxy** [comment] 2024-08-12 13:30
Fixed via #376 - closing issue.

**Closed by dnzxy** 2024-08-12 13:30 UTC
Labels: bug, Pre 1.0
