### ISSUE TITLE
Trio Notification Glucose Defaults to mg/dl

### ISSUE THREAD

**Issue by SjpStanley** [nightscout/Trio#400] opened 2024-08-29 16:20 UTC
## Describe the bug
Glucose units are set to mmol in preferences.
Enable notifications for Trio in iPhone settings
Enable glucose settings under Trio/Notifications
Wait for notification.

This is observed when using Libre 2, not sure if same applies if using Dexcom.

Related (second bug?)
If you also enable glucose notification under CGM Configuration this generates a second notification correctly using mmol units.

However, if you then disable the glucose notifications  under Trio Settings/Notifications then the CGM mmol notification stops presenting and you now get the Trio notification with mg/dl units again.

## To Reproduce
*Steps to reproduce the behavior:*
1. *Go to '...'*
2. *Click on '....'*
3. *Scroll down to '....'*
4. *See

## Expected behavior
*A clear and concise description of what you expected to happen.*

## Screenshots
Attached.

### Smartphone:
* Hardware: iphone 13 Pro
* OS Version: IOS 17.5.1

### Pump:
* Manufacturer: *[e.g. Insulet]*
* Model: Omnipod Dash

### CGM:
* Device: Libre 2
* Manager app: Libre Direct

### Trio Version:
* Version 0.2.0
![IMG_1287](https://github.com/user-attachments/assets/846933c8-bfb7-426a-9f7a-bee0a98aa194)

**Comment by Sjoerd-Bo3** [comment] 2024-08-29 16:28
@SjpStanley This was already in an earlier closed Issue #40 
But cannot be fixed on Trio's side, right @dnzxy Or has that changed?

Maybe the best is to use xDrip4iOS for libre's?

**Comment by dnzxy** [comment] 2024-09-28 23:29
This is an issue with the underlying dependency, not in our power to solve. 
Also duplicate of #40. Closing.

**Closed by dnzxy** 2024-09-28 23:29 UTC
Labels: bug, duplicate
