### ISSUE TITLE
Unify how settings are stored

### ISSUE THREAD

**Issue by DreyCon-Raphael** [nightscout/Trio#361] opened 2024-07-25 11:55 UTC
## Is your feature request related to a problem? Please describe.
When editing settings in Trio subviews behave differently.

Some settings are stored and activated immediatle (I) by leaving the edit field, others need to be saved by pushing a button (B). 
| settings view | storing behavior |
| --- | --- |
| Preferences | (I) |
| Pump Settings | (B)** |
| Meal Settings | (I) |
| Basal Profile | (B)** |
| Insulin Sensitivity | (B)* |
| Carb Ratios | (B)* |
| Target Glucose | (B)* |
| Autotune | (B)*** |

- (I) is stored immediately
- \* ist stored via a button labeled "Save"
- ** is stored via a button called "Save on Pump"
- *** is stored via a button called "Save as your Normal Basal Rates"

Despite that this is only a UX thing, I suggest to unify this to always have a save button. This could also be used as a hook to push the new changes to NS.

## Describe the solution you'd like
1. Use the same save button everywhere
  - regardless of whether values are stored
    - only in app for "cosmetically" changes (e.g.: hours displayed on home view)
    - for basic pump behaviour (e.g. offline basal rates) or
    - for oref's needs (e.g. ISF, CR)
2. prepare a hook for pushing changes to NS with a "valid from" timestamp
3. (optional) ask for individual notes to the made changes (such as an optional commit message). Users can rethink decisions made based on their notes.

## Additional context
Save on Pump
![image](https://github.com/user-attachments/assets/9b2ad62f-3a12-41a5-9d91-e6e02f59c45a)
Save
![image](https://github.com/user-attachments/assets/961fae5f-ccc3-49a6-a90e-b8c058a332ee)
Save as your Normal Basal Rates
![image](https://github.com/user-attachments/assets/35afb6c9-ba6c-4af3-a508-edacff8ef1d4)

## User Impact
- Needs the User to ALWAYS hit a save button for changes to take effect.
- Enables the user to discard changes made if not having previous values noted anywhere
- Enables storing history of changes made

**Comment by dnzxy** [comment] 2024-07-26 23:52
Duplicate of #98. Closing.

**Closed by dnzxy** 2024-07-26 23:52 UTC
Labels: enhancement, needs-triage
