### ISSUE TITLE
Duplicated carb entries

### ISSUE THREAD

**Issue by pheltzel** [nightscout/Trio#175] opened 2024-05-11 14:02 UTC
--Added 30g of carbs at 5:58 a.m. on May 11 (log attached).
--But 2 entries appeared in the History screen in Trio

![IMG_9008](https://github.com/nightscout/Trio/assets/1165092/7aa70970-936e-46ed-a7b4-d7b32a631cb5)
![IMG_9009](https://github.com/nightscout/Trio/assets/1165092/e4996f15-a33f-4b82-939e-a1c4840acb6e)

I deleted the second errant entry. So sorry, don't have a screenshot for that. Should have captured that first. 

--Running Trio v0.1.0
--Branch: dev6f862aa
--Omnipod Dash, G7
 
[log-dupe-carb-entry.txt](https://github.com/nightscout/Trio/files/15283019/log-dupe-carb-entry.txt)

This may be an intermittent bug -- and possibly only a display issue. Same issue was reported here in the iAPS Github Issues area and may be related to writing to Health:

https://github.com/Artificial-Pancreas/iAPS/issues/450

A potential fix was suggested here:
https://github.com/Artificial-Pancreas/iAPS/pull/564

Could be user error, but I'm pretty sure I didn't enter this twice. 

I still have iAPS 4 on my iPhone 15, not sure if that could be related. I've been seeing how it differs from what Trio advises.

But I've experienced the bug reported above (Issue 450 in iAPS), and it was thought to be Apple Health related, so I turned it off. I've turned it off in Trio now as well.

**Comment by itsmojo** [comment] 2024-05-15 15:16
Not sure if this is another example of this problem or something else. On 5/14/24 I had an incident where I wanted to log some food with carbs, fats & proteins, but hitting Save and continue wasn’t taking the app to the next screen after multiple attempts. It appeared as if the Trio app was locked up. I evidently got out of that screen (using Close? I believe, but I’m not sure), but then I found that I had created many duplicate carb entries (I’d guess 70 - ~7 with my future carbs for each of my maybe 10 attempts to try to Save and continue with no response) that had to all be manually deleted. Unfortunately I was in a conversation & in a bit of a rush to recover when this happened and didn’t grab any screen shots or take careful mental notes of the details. I was running a version of Trio that was cloned on May 11 at 2 pm PDT at the time  of this incident.

**Comment by pheltzel** [comment] 2024-05-15 15:37
Thanks @itsmojo (also nice to see you again!) This absolutely be user error. 

One thing I mentioned in the original post was that I had a functioning version of iAPS 4 on my phone at the time. I was surprised to see at one point that entries made in iAPS would show up in Trio. I don't think that happened here -- it was before 6 a.m. and a lot of is possible -- but I wanted to mention.

I also raised this issue because I had definitely seen multiple errant carb entries in iAPS that I did not input. That was confirmed by another user who reported the same issue at the same time with his kid--there were many, many errant entries for them, at the same time. My initial thought was: Are Health and Nightscout somehow double counting? Both were on, and like I said, I had seen it before. And I had iAPS on there still, potentially talking to NS and Health, though not connected to a pod, of course. It's possible I mixed a mean margarita of competing possible data entries.

So I am asking Andy to send my log from this time to see if that sheds any light. I know I didn't double tap this time, but it's totally possible I still screwed it up. Again, I had experienced double counting in iAPS and just wanted to make sure that isn't happening also in Trio.

**Comment by itsmojo** [comment] 2024-05-15 23:00
> This absolutely be user error.

I disagree. The app should not lock up and it certainly should not continue to add duplicate carb entries each time the "Save and continue" button is pressed if it does freeze up trying to save a carb entry. Sounds it could a different issue than the duplicate carb entry issue originally reported here though.

**Comment by pheltzel** [comment] 2024-05-16 01:00
If it's error, it would be mine. If you add carbs, tap Save and Continue, then do it again, you get 2 carb entries in History.

But I don't think I did that. I think 2 entries showed up when only 1 was entered. And that happened to me in iAPS 3, a couple months ago.

**Comment by pheltzel** [comment] 2024-05-16 01:05
![image](https://github.com/nightscout/Trio/assets/1165092/8df144e4-da65-4479-8bb7-48a388abfdd0)

It surprised me to see carb entries made in Trio appear in the iAPs History. This screenshot of the iAPS History shows carb entries made today in Trio.

**Comment by marionbarker** [comment] 2024-05-16 03:35
I see this as well but with Loop carb entries showing in Trio. I use Loop but also have Trio on the phone (connected to pump simulator and using Nightscout as a CGM). I have Apple Health turned off. Trio must be downloading my carbs (uploaded by Loop) from Nightscout.

**Comment by pheltzel** [comment] 2024-05-16 04:50
Ah, that's interesting. I have a copy of the latest iAPS on my phone but not set up. And though most of the settings are the defaults, my Nightscout info is there. Basal, CR, ISF are whatever you see as a new user, but it saved my NS URL and password.

**Comment by dsnallfot** [comment] 2024-05-16 05:51
Ok folks. 

It seems like there is at least three aspects to this duplicate carbs that needs to be fixed (the first two possible easier to fix than the third):

1. Save button in meal view should probably be deactivated after tapping it the first time (to block potential double tapping before entering bolus view when app response is slow for whatever reason)

2. Nightscout fetch of treatments entered by other uploaders/in careportal (carbs/temp targets) should be possible for the user to enable/disable by toggle in settings to avoid not expected carbs from Loop or iAPS etc showing up as it does today by default as mentioned by @marionbarker and @pheltzel above (which I think @Sjoerd-Bo3 is working on?)

3. Figure out why duplicates sometimes are created in datatable and apple health but not seemingly affecting COB and preventing this. (This is what I tried to address in the fix 564 that @dnzxy have concluded does not help). 

4. Maybe more aspects to this that I’ve not identified

**Comment by dnzxy** [comment] 2024-05-16 06:06
Good summary. 

I suspect No. 1 is an issue with I/O latency around JSON files that makes the UI unresponsive and possibly data races / race conditions - there are *many* of those in the current backend. I don’t think this can really be addressed with the current state of the app and is more so addressable when a more far reaching rewrite of the backend is introduced 😊 

That’s also why we‘ve concluded that No. 3 isn’t a fix, as it just puts stuff on a different queue, but maybe a bandaid to those data races / race conditions / thread unsafe processes. You did rightfully describe it as a „maybe fix, needs testing“ in the PR, which is on point 👍😅

I don’t think that allowing other apps to influence Trio is a thing we‘d want, so No. 2 should probably not only be toggleable, but disallowed. Filtering for an `enteredBy` is probably the fix for this portion of the bug. 

While this very much looks to be an actual bug, I‘ve personally never come across it in almost a year of using iAPS / Trio, so not sure what type of contexts need to be in place for this to happen. Maybe older phone with limited memory? Paul, Joe, what phones are you using?

I also think that the issue of having other apps uploading to NS and Trio then fetching those carb entries is not really related to this issue (#175), but a different one, and we should probably record it as such and keep it separate from this one here.

**Comment by dsnallfot** [comment] 2024-05-16 06:44
I had it happen at least two times (that I've noticed it) last year on my son's iPhone 12 mini. 

But since switching to iPhone 13 mini, disabling Apple health and applying that separate queue thing for setupTreatments() it had not occurred again. 

Been trying to force it to occur in simulator with AH enabled (while testing the separate queue) without success. It's seems almost impossible to reproduce the bug since it's so infrequent.

**Comment by dnzxy** [comment] 2024-05-16 07:20
It shouldn’t be related to AH, as iAPS/Trio does not read from AH (read as in include read samples upon storage to carb history to be added to COB to be dosed for), unless I am misremembering things.

**Comment by AndreasStokholm** [comment] 2024-05-16 08:39
That shouldn't be an issue no. If AH fails writing now it will not crash the app, but the AH reporting will be incorrect for that one write (which will in many cases show up later as the app is very verbose with what it writes and updates in AH).

Sorry for not responding to this ticket sooner @bjornoleh, I missed the notification 😬

**Comment by itsmojo** [comment] 2024-05-16 08:46
@dnzxy My iPhone is a 15 Pro Max 512 GB running iOS 17.4.1. In the past I have occasionally noticed brief hangs trying to save in the meal view when running iAPS & Trio, but in this most recent incident it was much more prolonged hang.

**Comment by bjornoleh** [comment] 2024-05-16 13:27
Speaking of hangs, I have noticed some that may or may not be related to the above. Just wanted to mention it in case there is something in common. 

I typically have several builds on my phone for testing in sim mode, using different bundle IDs. 

When opening one of these a long time since the last time it ran, it will typically hang initially. Usually, it will become responsive again after several seconds (10+ sec). I believe this is when there is no data from the last 24 hours in the log files (the files will contain old data at startup). Perhaps it’s related to purging the json files?

I have also had situations where the app never became responsive, and had to be uninstalled. This goes back to previous versions of the project (iAPS).

**Comment by pheltzel** [comment] 2024-05-16 16:54
@dnzxy I'm using an iPhone 15 Pro/iOS 17.3.1/256GB. 

I can document No. 2 @dsnallfot described as a PR if that's helpful to break these up. That one I can recreate and get screen captures of easily.

**Comment by dnzxy** [comment] 2024-05-16 17:24
Okay I don’t think it’s phone / memory related then, as both you and Joe are running new and performant hardware. Bummer, I had hoped it’s due to lack of memory 🫠

If you could record a second issue, that would be super nice, thank you 🙏

**Comment by pheltzel** [comment] 2024-05-18 18:03
Andy was unable to provide the NS Pro logs, they aren't stored for very long. 

If this happens again it would be good to capture asap the Trio log, screenshots of the dupe carbs in history, NS report and these files:

carbhistory.json
pumphistory-24h-zoned.json

I tried entering carbs in iAPS 4 dev, with Health and my NS account connected in the app, but I'm no longer seeing carb entires made in iAPS appear in Trio. 

I do see carb entries made in Trio appear I. the iAPS history.

**Comment by Stefan261288** [comment] 2024-05-19 07:08
I had this happening to me few days back where I had entered carbs and was expecting to bolus. The app did not respond when I clicked "Save and continue", and I had ended up adding 50g of carbs 4 times before I realized there was something wrong. 
Obviously I did not bolus and I could quickly delete the extra carbs afterwards, but 200g of carbs would affect the automatic provisions of insulin.

If it happens again I will follow the instructions above to log it. 
This cannot be identified as a user error, and it does not have to do with carbs coming from other apps (I only enter data in Trio). 

I agree with previous poster that somehow blocking carb entries would be a good way to ensure it does not happen. Possibly blocking duplicate carb entries for X seconds.

**Comment by bjornoleh** [comment] 2024-05-22 09:16
> That shouldn't be an issue no. If AH fails writing now it will not crash the app, but the AH reporting will be incorrect for that one write (which will in many cases show up later as the app is very verbose with what it writes and updates in AH).
> 
> Sorry for not responding to this ticket sooner [@bjornoleh](https://github.com/bjornoleh), I missed the notification 😬

I assigned this issue to you due to the impression that this was related to AH. That does not seem to be the case, so I will remove that assignment in case someone else wants to get busy with this :-)

**Comment by MikePlante1** [comment] 2024-05-30 02:05
@dsnallfot :
> 1. Save button in meal view should probably be deactivated after tapping it the first time (to block potential double tapping before entering bolus view when app response is slow for whatever reason)?

I just submitted a PR for this: #248

**Closed** 2024-06-01 14:59 UTC
Labels: bug
